### ISSUE TITLE
Linux Crash: Segfault immediately after Printer Error dialog closes

### ISSUE THREAD

**Issue by deftdawg** [bambulab/BambuStudio#798]
[Relates to #12 - this should probably be fixed prior to an final official Linux AppImage release]

When a printer has an error a dialog with an error code appears with `Confirm` button.   Once this button is pressed, BambuStudio crashes.

This was observed with BambuStudio running on KDE Neon (Ubuntu 22.04 LTS) and SteamOS 3.4/HoloISO (Arch)...  The printer had an error and both instances crashed after hitting `Confirm`.

Attached is the GDB backtrace

```
[New Thread 0x7fff081b2640 (LWP 209657)]
[Thread 0x7fff081b2640 (LWP 209657) exited]

Thread 1 "bambustu_main" received signal SIGSEGV, Segmentation fault.
0x000055555852851c in wxWebRequestImpl::ProcessStateEvent(wxWebRequest::State, wxString const&) ()
(gdb) #0  0x000055555852851c in wxWebRequestImpl::ProcessStateEvent(wxWebRequest::State, wxString const&) ()
#1  0x0000555558912870 in wxEvtHandler::TryHereOnly(wxEvent&) ()
#2  0x00005555589128bf in wxEvtHandler::ProcessEventLocally(wxEvent&) ()
#3  0x0000555558912969 in wxEvtHandler::ProcessEvent(wxEvent&) ()
#4  0x00005555589121de in wxEvtHandler::ProcessPendingEvents() ()
#5  0x0000555558830607 in wxAppConsoleBase::ProcessPendingEvents() ()
#6  0x000055555873f9b5 in wxApp::DoIdle() ()
#7  0x000055555873faa7 in wxapp_idle_callback ()
#8  0x00007ffff6d6fc24 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff6dc46f8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff6d6f293 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff75aecfd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x000055555874f675 in wxGUIEventLoop::DoRun() ()
#13 0x0000555558862681 in wxEventLoopBase::Run() ()
#14 0x0000555558830f43 in wxAppConsoleBase::OnRun() ()
#15 0x00005555588b2e97 in wxEntry(int&, wchar_t**) ()
#16 0x000055555649d43b in Slic3r::GUI::GUI_Run(Slic3r::GUI::GUI_InitParams&) ()
#17 0x0000555555d49cd3 in Slic3r::CLI::run(int, char**) ()
#18 0x0000555555c9d829 in main ()
(gdb) A debugging session is active.

        Inferior 1 [process 205849] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```

**Comment by bambu123** [comment]
Maybe fixed.
